version: '3.8'
services:
  tuitui-chat-green:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    ports:
      - "8446:8443"
    # 이미지 이름
    image: tuitui-chat-blue
    # 컨테이너의 이름
    container_name: tuitui-chat-green
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    networks:
      - tuitui-chat-network

networks:
  tuitui-chat-network:
    external: true
    driver: bridge